### ISSUE TITLE
Version 0.9.27 does not open

### ISSUE THREAD

**Issue by itsmefox** [datatobridge/arcdps-uploader#12]
Version 0.8 worked with no problems but with the new version (0.9.27) and the new ArcDps (Nov 17 2020) version I can't open the uploader window any more. The d3d9_uploader.dll also no longer listed as extension in the arcdps.log file.

**Comment by datatobridge** [comment]
Please post the log found inside your Guild Wars 2 folder (addons/uploader/uploader.log)

**Comment by itsmefox** [comment]
Ahh it seems I did not had the latest Visual C++ x64 redistributable :) Thx for the info.
