### ISSUE TITLE
addon loader/manager support

### ISSUE THREAD

**Issue by megai2** [datatobridge/arcdps-uploader#13]
Hi. 
We recived a pull request to add this addon to unofficial addon manager.
But i faced a problem when testing it.

Arcdps lives in "gw2 root folder"/addons/arcdps/ folder when installed via addon manager
and all addons that are based on arcdps, will live in same directory.

Uploader just gives std::filesystem::filesystem_error exception and crashes when installed this way.
Will be good if you can correct this error.

ref: https://github.com/gw2-addon-loader/Approved-Addons/pull/5

**Comment by datatobridge** [comment]
@megai2 Please give 0.9.4 a try. I'm not sure I saw that exact issue, but I was able to successfully use the addon manager with these changes.
https://github.com/datatobridge/arcdps-uploader/releases/tag/arcdps_uploader_v0.9.4.38

**Comment by megai2** [comment]
Looks like all works fine now
