### ISSUE TITLE
[Important] Push the uploader to imgui 1.80

### ISSUE THREAD

**Issue by MoXAriApph** [datatobridge/arcdps-uploader#18]
ArcDPS has just moved to imgui 1.80, the uploader no longer works in current version(s) of Arc.

**Comment by datatobridge** [comment]
Thanks for heads up, I'll work on this soon.

**Comment by datatobridge** [comment]
@MoXAriApph Fixed in the latest release. Please let me know if you run into any issues.

https://github.com/datatobridge/arcdps-uploader/releases/tag/arcdps_uploader_v0.9.5.40

**Comment by datatobridge** [comment]
Fixed by d45ec84f668cd323bfaa5f4ff75b526ab6b94eb7
