### ISSUE TITLE
No logs shown ingame

### ISSUE THREAD

**Issue by JFrisch85** [datatobridge/arcdps-uploader#4]
A few days ago it happened again that my uploader is working (I can open the ingame window), but no logs are shown. Refreshing doesn't work anymore, no logs shown and I have no clue why and what to do about it. Any suggestions what could cause this problem?

**Comment by JFrisch85** [comment]
Seems like it vanished on its own like last time, but I'm still curious what could potentially cause this issue.

**Comment by JFrisch85** [comment]
And yet again the uploader loads but can't find any logs at all (see empty window in the screenshot attached) - why is this happening?
![gw271](https://user-images.githubusercontent.com/33455667/80622148-afcdcd00-8a48-11ea-8c7c-dafe9d867cee.jpg)

**Comment by datatobridge** [comment]
#5

0.8 was unable to deal with newer logs, see the linked issue. Sorry for the delay, I don't play much anymore and don't receive notification when an issue is posted.
