### ISSUE TITLE
[Bug] Logs not being loaded

### ISSUE THREAD

**Issue by MoXAriApph** [datatobridge/arcdps-uploader#5]
Addon does not load logs from encounters, Refresh button does nothing

Logs in default directory, GW2 is on an SSD separate from where the logs are stored.

E.g.
> "D:\Guild Wars 2"
> "C:\Users\Username\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs"

**Comment by MoXAriApph** [comment]
Update, latest build (0.9.1) works, however, viewing logs in-game doesn't function
Logs from the past 3 days automatically upload with no prompt though, which is slightly annoying on first start

**Comment by MoXAriApph** [comment]
@datatobridge

**Comment by datatobridge** [comment]
Thanks for the ping. I meant to publish 0.9.1 a while ago. 0.8 is unable to deal with newer logs.

From version 0.9 on, logs are automatically uploaded when you are not in combat. Each log will only be uploaded once and you can go back and get the dps.report's permalink anytime. I'm unable to maintain the built-in parser so in-game log previews on hover are removed for now. It is possible to retrieve the already parsed data from dps.report and display that, but I haven't implemented that and I'm not sure when/if I will. I added Discord webhook integration and mainly use this tool to post logs in my static's discord channel automatically without having to run an external tool.

I understand that changes the use-case for this tool so I will update the readme to indicate these changes and I'll publish a prebuilt 0.9.1 build.
