### ISSUE TITLE
Window extends to full screen width

### ISSUE THREAD

**Issue by good-live** [datatobridge/arcdps-uploader#7]
It's a bit hard to explain, but basically when i open the ingame window using Alt Shift U it starts in the normal size and then extends to the full size of the screen. I attached a screen how it looks after the window extended fully. (If needed i can also make a small video)

![image](https://user-images.githubusercontent.com/10183190/99905189-b5824d00-2ccf-11eb-8897-a46686515ffc.png)

I'm using the version 0.9.27

**Comment by datatobridge** [comment]
Are you using a custom font size and/or font? Doesn't look like it but making sure. Otherwise, can you tell me your desktop resolution?

**Comment by good-live** [comment]
No im not using a custom font. My resolution is full hd. (1920*1080)

**Comment by itsmefox** [comment]
I have this bug too. Also no custom font and a resolution of: 3440x1440

**Comment by datatobridge** [comment]
Please try 0.9.3, this issue should be fixed.
